import os
import glob
import re
import openai
import json
import time
from absl import flags
from api_cost import api_cost
from transformers import AutoTokenizer

try:
    from vllm import LLM, SamplingParams
    import ray
    from tpu_utils import prevent_cross_region
except ImportError as err:
    print(err)
    pass


FLAGS = flags.FLAGS
flags.DEFINE_string('openai_key', glob.glob(os.path.abspath('../../../*openai*'))[0], 'path to openai key')
# flags.DEFINE_string('tmp_dir', glob.glob(os.path.abspath('../../*tmp*'))[0], 'path to tmp directory to download vLLM models')

flags.DEFINE_string('model', 'gpt-3.5-turbo', 'gpt-3.5-turbo / default, gpt-4-turbo, gpt-4o, gpt-3.5-turbo-instruct, meta-llama/Llama-2-70b-hf')
flags.DEFINE_integer('iterations', 1, 'integer number of iterations (default 1)')
flags.DEFINE_boolean('verbose', True, 'actually print out json? (will still show tqdm bar if False)')
flags.DEFINE_boolean('write', False, 'write to file? name format is generated as output_gym_<exo/exn/s>_<once/turns>_<sof1>_<sof2>_<iterations>_<taxonomy>.json')
flags.DEFINE_string('persuasion_taxonomy', 'none', 'what kind of persuasion taxonomy to use, if any? (none/default, full, reduced, no_examples)')
flags.DEFINE_integer('convo_length_limit', 10, 'upper limit of conversation length (10/default)')
flags.DEFINE_integer('gpus', 1, 'number of gpus to run inference on (1/default)')
flags.DEFINE_integer('seed', 0, 'seed used for random point generation')
flags.DEFINE_string('model_dir', '/persuasion/models', 'directory to download model weights, use gcsfuse to mount bucket on TPUs')
flags.DEFINE_integer('max_tokens', 256, 'upper limit on tokens generated by model (256/default)')
flags.DEFINE_boolean('deception', False, 'whether to use deceptive prompting (False/default)')
flags.DEFINE_string('gen_format', 'turns', 'in turns (turns / default), all at once (once)')
flags.DEFINE_string('theory_of_mind', 'none', 'which theory of mind experiment to use (none/default, theory_of_mind, half_theory_of_mind)')
flags.DEFINE_boolean('tpu', False, 'whether we are using the TPUs for vLLM inference (False/default)')
flags.DEFINE_integer('max_guess_tries', 10, 'how many times to rerun guess generation if output is malformed (10/default)')
flags.DEFINE_boolean('half_agent', False, 'one agent prompted with deception/persuasion taxonomy and the other is not (False/default)')
flags.DEFINE_string('config_file', None, 'config file to set up experiment, overrides flags (None/default)')
flags.DEFINE_boolean('chain_of_thought', False, 'whether to query each agent each turn on why they responded in the way they did (False/default)')

config = {}
# see reset_stats for values
stats = {}

def set_flag_variables():
    for flag in FLAGS:
        config[flag] = FLAGS[flag].value

def extract_ordered_tuples(text):
    pattern = r'\(([^)]+)\) <EOD>'
    match = re.findall(pattern, text)
    if match:
        ordered_tuples = [tuple(map(int, lst.split(','))) for lst in match]
        return ordered_tuples
    else:
        return None

def load_stats_file(write_file):
    '''
    Creates write_file path and file if it doesn't exist
    Otherwise load and determine index_offset of file
    Returns index_offset
    '''
    index_offset = -1
    if config['write']:
        os.makedirs(os.path.dirname(os.path.abspath(write_file)), exist_ok=True)
    if config['write'] and not os.path.exists(write_file):
        with open(write_file, "w") as f:
            print('written!!')
            json.dump([], f)
            index_offset = 0
    if config['write'] and index_offset == -1:
        with open(write_file, "r") as f:
                index_offset = len(json.load(f))
    return index_offset

def write_stats(write_file):    
    '''
    Appends stats to end of write file
    '''
    if config['verbose']:
        print("Writing to file!")
    with open(write_file, "r") as f:
        conversations = json.load(f)
    conversations.append(stats)
    with open(write_file, "w") as f:
        json.dump(conversations, f, indent=4)

vllm_alias = {
    'mistral': 'mistralai/Mistral-7B-v0.3',
    'mixtral': 'mistralai/Mixtral-8x7B-v0.1',
    'mistral-instruct': 'mistralai/Mistral-7B-Instruct-v0.3',
    'mixtral-instruct': 'mistralai/Mixtral-8x7B-Instruct-v0.1',

    'gemma': 'google/gemma-7b',
    'gemma-2-27b': 'google/gemma-2-27b',
    'gemma-2-27b-it': 'google/gemma-2-27b-it', # instruction tuned
    
    'Llama-3-70B': 'meta-llama/Meta-Llama-3-70B',
    'Llama-3-8B': 'meta-llama/Meta-Llama-3-8B',
    'Llama-3.1-405B': 'meta-llama/Meta-Llama-3.1-405B',
    'Llama-3.1-8B': 'meta-llama/Meta-Llama-3.1-8B',
    'Llama-3.1-70B': 'meta-llama/Meta-Llama-3.1-70B',
    'Llama-3.1-405B-Instruct': 'meta-llama/Meta-Llama-3.1-405B-Instruct',
    'Llama-3.1-70B-Instruct': 'meta-llama/Meta-Llama-3.1-70B-Instruct',
    'Llama-3.1-8B-Instruct': 'meta-llama/Meta-Llama-3.1-8B-Instruct'
}

llm = None

# run 'ray start --head' in bash first!
def setup_vllm():
    if config['gpus'] > 1:
        ray.init(ignore_reinit_error=True) 

    global llm
    if config['model'] in vllm_alias:
        if vllm_alias[config['model']] == 'meta-llama/Meta-Llama-3.1-70B' or vllm_alias[config['model']] == 'meta-llama/Meta-Llama-3.1-70B-Instruct':
            llm = LLM(model=vllm_alias[config['model']], tensor_parallel_size=config['gpus'], download_dir=config['model_dir'], gpu_memory_utilization=1, max_model_len=16384)
        else:
            llm = LLM(model=vllm_alias[config['model']], tensor_parallel_size=config['gpus'], download_dir=config['model_dir'])
    else:
        try:
            llm = LLM(model=config['model'], tensor_parallel_size=config['gpus'], download_dir=config['model_dir'])
        except:
            print('Info: Passing vllm setup')

def set_global_variables(config_file):
    with open(config_file, "r") as f:
            config_loaded = json.load(f)
    for key in config_loaded.keys():
        config[key] = config_loaded[key]

def init():
    set_flag_variables()
    if FLAGS.config_file:
        set_global_variables(FLAGS.config_file)
    with open(FLAGS.openai_key, 'r') as f:
        openai.api_key = f.read().rstrip('\n')

def completion_create_helper(prompt):
    ret = '' # return the output ret at the end and use to calculate cost

    if config['model'] == "gpt-3.5-turbo-instruct": # previously davinci, but that's now deprecated
        ret = openai.Completion.create(
                model="gpt-3.5-turbo-instruct",
                prompt=prompt,
                temperature=0.8,
                max_tokens=config['max_tokens'],
                top_p=1,
                frequency_penalty=0,
                presence_penalty=0
        )
        ret = ret.choices[0].text.strip()
    elif config['model'] in ["gpt-3.5-turbo", "gpt-4-turbo", "gpt-4o", 'gpt-4o-mini']:
        if config['gen_format'] == 'turns':
            ret = openai.ChatCompletion.create(
                model=config["model"],
                messages=[{"role": "system", "content": prompt}],
                max_tokens=config['max_tokens']
            )
            ret = ret.choices[-1].message.content
        elif config['gen_format'] == 'once': # deprecated case, don't use
            ret = openai.ChatCompletion.create(
                model=config["model"],
                messages=[{"role": "system", "content": prompt}],
                max_tokens=config['max_tokens']
            )
            ret = ret.choices[-1].message.content
        else:
            raise IllegalFlagValueError
    else: # assume huggingface model in general case with full path
        sampling_params = SamplingParams(temperature=0.8, top_p=0.95, max_tokens=config['max_tokens'])

        # can use llm.llm_engine.tokenizer.tokenizer.apply_chat_template instead of loading in a separate tokenizer
        if config['model'] in vllm_alias:
            tokenizer = AutoTokenizer.from_pretrained(vllm_alias[config['model']])
        else:
            print('Attempting to use model', config['model'])
            tokenizer = AutoTokenizer.from_pretrained(config['model'])
        messages = [
            {"role": "user", "content": prompt}
        ]
        if tokenizer.chat_template:
            prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        output = llm.generate([prompt], sampling_params)
        ret = output[0].outputs[0].text
        if config['verbose']:
            print(ret)

    if config['model'] not in vllm_alias:
        stats['running_cost_for_iteration'] += api_cost(prompt=prompt, answer=ret, model=config['model'])
        if config['verbose']:
            print(f"RUNNING COST FOR ITERATION SO FAR: {stats['running_cost_for_iteration']}")
    
    return ret

def completion_create(prompt, keep_trying=True):
    try:
        return completion_create_helper(prompt)
    except (openai.APIError, openai.OpenAIError) as e:
        print("ERROR", e)
        print("sleeping for 10 seconds.")
        time.sleep(10)
        if keep_trying:
            return completion_create(prompt, keep_trying)
        else:
            return None