"""System-level mimic validation: do COMPETITION OUTCOMES match?

Row-level fidelity (validate_deception_mimics.py) shows each *claim* matches the
real LLM. This script tests the stronger, system-level claim: when five mimics
play the full 12-round game, do the *outcomes* (catch rate, win rate, final
trust) match what the real LLMs produced — on the SAME truth seeds?

This is the capstone validity check. It directly probes the behavioral-cloning
distribution-shift risk: the mimics were trained on states generated by real
LLMs, but in self-play the mimics generate the states. If outcomes still track,
the surrogate holds; if they diverge, we quantify the drift.

Method:
  1. Read the sweep manifest -> the 200 real episodes (truth_seed, known, penalty).
  2. REAL outcomes: read each slot's episode_log.json (already on disk).
  3. MIMIC outcomes: replay each config with the Mimic-<LLM> loadout through the
     SAME HTTP game engine, matched truth_seed/known/penalty/preferences.
  4. Compare per-model aggregates + paired per-episode arrays; write a report and
     a paired-bar figure.

Requires the server running (default http://localhost:8010).

Usage:
    python -m simulation.validate_mimic_outcomes [--limit N] [--parallel 8]
"""
from __future__ import annotations

import argparse
import json
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import numpy as np

from simulation.run_deception_competition import run_one, find_or_create_folder

HERE = Path(__file__).parent
RUNTIME = HERE / ".runtime"
SAVE_SLOTS = RUNTIME / "save_slots"
MANIFEST = HERE / "datasets" / "deception_sweep_manifest.json"
OUT_REPORT = HERE / "datasets" / "deception_outcome_report_v1.json"
FIG_DIR = HERE / "exports" / "figures"

MODEL_ORDER = ["GPT-5.4", "Opus", "Pro", "Grok", "Llama"]


def _episode_log_path(slot_id: str) -> Path:
    return SAVE_SLOTS / slot_id / "auction_exports" / "deception_episode" / "episode_log.json"


def _read_log(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError):
        return None


def _outcomes_from_log(log: dict) -> dict[str, dict]:
    """Per-alias outcome rates from one episode log."""
    n = max(1, int(log.get("num_rounds", 12)))
    out = {}
    for a in log.get("agents", []):
        out[a["alias"]] = {
            "catch_rate": a.get("caught_count", 0) / n,
            "win_rate": a.get("win_count", 0) / n,
            "final_trust": float(a.get("final_trust", 0.0)),
        }
    return out


# ── Phase 1+2: gather real outcomes, replay mimic outcomes ───────────────────

def gather_real(manifest: list[dict]) -> dict:
    """Map truth_seed|known -> {alias: outcomes} for every ok real episode."""
    real = {}
    missing = 0
    for e in manifest:
        if not e.get("ok"):
            continue
        log = _read_log(_episode_log_path(e["slot_id"]))
        if not log or not log.get("complete"):
            missing += 1
            continue
        key = (int(log.get("truth_seed", e.get("truth_seed", -1))),
               int(log.get("partial_known_count", e.get("known", 5))))
        real[key] = {
            "outcomes": _outcomes_from_log(log),
            "penalty": float(log.get("penalty", e.get("penalty", 1.0))),
            "threshold": float(log.get("threshold", 0.4)),
            "preferences": list(log.get("preferences", [])),
            "loadout": list(log.get("selected_models", [])),
            "truth_first_round": (log.get("rounds") or [{}])[0].get("truth"),
        }
    if missing:
        print(f"  note: {missing} real episodes had no complete log (skipped)")
    return real


def replay_mimics(base: str, real: dict, *, parallel: int, timeout_s: float,
                  poll_s: float) -> dict:
    """Replay each real config with the mimic loadout; return matched outcomes."""
    folder_id = find_or_create_folder(base, "Mimic Outcome Replay")
    items = list(real.items())
    print(f"  replaying {len(items)} episodes with mimic loadout (parallel={parallel})")

    lock = threading.Lock()
    done = {"n": 0}
    results: dict = {}

    def _task(idx_key_cfg):
        i, (key, cfg) = idx_key_cfg
        truth_seed, known = key
        loadout = ["Mimic-" + m for m in (cfg["loadout"] or MODEL_ORDER)]
        mode = "deception_competition" if known >= 5 else "deception_competition_partial_info"
        res = run_one(
            base,
            folder_id=folder_id,
            seed=truth_seed,                 # deterministic; truth_seed drives the schedule
            truth_seed=truth_seed,
            slot_name=f"MimicReplay ts{truth_seed} k{known}",
            loadout=loadout,
            mode=mode,
            known_attrs=known,
            threshold=cfg["threshold"],
            penalty=cfg["penalty"],
            num_rounds=12,
            preferences=cfg["preferences"] or None,
            poll_interval_s=poll_s,
            timeout_s=timeout_s,
        )
        rec = {"ok": bool(res.get("ok")), "error": res.get("error")}
        if res.get("ok") and res.get("slot_id"):
            log = _read_log(_episode_log_path(res["slot_id"]))
            if log and log.get("complete"):
                # Mimic episodes log aliases as "Mimic-<LLM>"; strip the prefix so
                # they key by the same model name as the real outcomes.
                raw = _outcomes_from_log(log)
                rec["outcomes"] = {a[len("Mimic-"):] if a.startswith("Mimic-") else a: v
                                   for a, v in raw.items()}
                rec["truth_first_round"] = (log.get("rounds") or [{}])[0].get("truth")
        with lock:
            done["n"] += 1
            tag = "ok " if rec.get("outcomes") else "FAIL"
            print(f"    [{done['n']:3d}/{len(items)}] {tag} ts{truth_seed} k{known}"
                  + ("" if rec.get("outcomes") else f"  ({rec.get('error')})"))
        return key, rec

    with ThreadPoolExecutor(max_workers=parallel) as ex:
        futs = [ex.submit(_task, ik) for ik in enumerate(items)]
        for f in as_completed(futs):
            key, rec = f.result()
            results[key] = rec
    return results


# ── Phase 3: compare + report + figure ───────────────────────────────────────

def _boot_mean_ci(a: np.ndarray, *, n_boot: int = 2000, seed: int = 0) -> list[float]:
    """95% bootstrap CI of the mean over episodes."""
    a = np.asarray(a, dtype=float)
    if len(a) == 0:
        return [float("nan"), float("nan")]
    rng = np.random.default_rng(seed)
    idx = rng.integers(0, len(a), size=(n_boot, len(a)))
    means = a[idx].mean(axis=1)
    return [round(float(np.percentile(means, 2.5)), 4), round(float(np.percentile(means, 97.5)), 4)]


def _boot_diff_ci(real: np.ndarray, mimic: np.ndarray, *, n_boot: int = 2000, seed: int = 0) -> list[float]:
    """95% bootstrap CI of the PAIRED mean difference (mimic − real). Resamples
    episode indices once and applies to both arms to preserve pairing."""
    r = np.asarray(real, dtype=float)
    m = np.asarray(mimic, dtype=float)
    if len(r) == 0:
        return [float("nan"), float("nan")]
    rng = np.random.default_rng(seed)
    idx = rng.integers(0, len(r), size=(n_boot, len(r)))
    diffs = (m[idx] - r[idx]).mean(axis=1)
    return [round(float(np.percentile(diffs, 2.5)), 4), round(float(np.percentile(diffs, 97.5)), 4)]


def compare(real: dict, mimic: dict) -> dict:
    """Per-model paired comparison of real vs mimic outcome rates."""
    METRICS = ["catch_rate", "win_rate", "final_trust"]
    paired = {m: {k: {"real": [], "mimic": []} for k in METRICS} for m in MODEL_ORDER}
    n_matched = 0
    n_setup_ok = 0
    for key, rcfg in real.items():
        mrec = mimic.get(key)
        if not mrec or not mrec.get("outcomes"):
            continue
        n_matched += 1
        # Sanity: confirm the replay faced the same truth (matched setup).
        if rcfg.get("truth_first_round") and mrec.get("truth_first_round"):
            if (np.allclose(rcfg["truth_first_round"], mrec["truth_first_round"], atol=1e-6)):
                n_setup_ok += 1
        ro, mo = rcfg["outcomes"], mrec["outcomes"]
        for model in MODEL_ORDER:
            if model in ro and model in mo:
                for k in METRICS:
                    paired[model][k]["real"].append(ro[model][k])
                    paired[model][k]["mimic"].append(mo[model][k])

    summary = {"n_matched_episodes": n_matched, "n_setup_verified": n_setup_ok, "per_model": {}}
    for model in MODEL_ORDER:
        rec = {}
        for k in ["catch_rate", "win_rate", "final_trust"]:
            r = np.array(paired[model][k]["real"], dtype=float)
            m = np.array(paired[model][k]["mimic"], dtype=float)
            if len(r) == 0:
                continue
            rec[k] = {
                "real_mean": round(float(r.mean()), 4),
                "mimic_mean": round(float(m.mean()), 4),
                "abs_diff": round(float(abs(r.mean() - m.mean())), 4),
                "paired_mae": round(float(np.abs(r - m).mean()), 4),
                "real_ci": _boot_mean_ci(r, seed=1),
                "mimic_ci": _boot_mean_ci(m, seed=2),
                "diff_ci": _boot_diff_ci(r, m, seed=3),
                "n": int(len(r)),
            }
        summary["per_model"][model] = rec
    return summary, paired


def make_figure(summary: dict) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({"font.family": "serif", "font.size": 8, "axes.linewidth": 0.6})
    FIG_DIR.mkdir(parents=True, exist_ok=True)

    metrics = [("catch_rate", "catch rate"), ("win_rate", "win rate"), ("final_trust", "final trust")]
    models = [m for m in MODEL_ORDER if m in summary["per_model"] and summary["per_model"][m]]
    x = np.arange(len(models))
    w = 0.38
    fig, axes = plt.subplots(1, 3, figsize=(9.0, 2.7))
    def _err(models_, key, arm):
        pts = np.array([summary["per_model"][m].get(key, {}).get(f"{arm}_mean", 0.0) for m in models_])
        cis = [summary["per_model"][m].get(key, {}).get(f"{arm}_ci", [np.nan, np.nan]) for m in models_]
        lo = np.array([c[0] for c in cis]); hi = np.array([c[1] for c in cis])
        return pts, np.vstack([pts - lo, hi - pts])

    for ax, (key, label) in zip(axes, metrics):
        real, err_real = _err(models, key, "real")
        mim, err_mim = _err(models, key, "mimic")
        ax.bar(x - w / 2, real, w, color="#3B6FB6", label="real LLM",
               yerr=err_real, capsize=2.5, error_kw={"lw": 0.8, "ecolor": "0.25"})
        ax.bar(x + w / 2, mim, w, color="#3B6FB6", alpha=0.55, hatch="////",
               edgecolor="white", linewidth=0.0, label="mimic",
               yerr=err_mim, capsize=2.5, error_kw={"lw": 0.8, "ecolor": "0.25"})
        ax.set_xticks(x)
        ax.set_xticklabels([m.replace("GPT-5.4", "GPT") for m in models], rotation=30, ha="right")
        ax.set_title(label, fontsize=9)
        ax.tick_params(labelsize=7)
    axes[0].set_ylabel("mean per episode")
    h, l = axes[0].get_legend_handles_labels()
    fig.legend(h, l, loc="upper center", ncol=2, frameon=False, bbox_to_anchor=(0.5, 1.07), fontsize=8)
    fig.suptitle("System-level fidelity: real-LLM vs. mimic competition outcomes (matched seeds)",
                 y=1.15, fontsize=9)
    for ext in ("pdf", "png"):
        fig.savefig(FIG_DIR / f"deception_outcome_parity.{ext}", dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {FIG_DIR / 'deception_outcome_parity.pdf'}  (+ .png)")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--base", default="http://localhost:8010")
    p.add_argument("--limit", type=int, default=0, help="Replay only the first N configs (0 = all).")
    p.add_argument("--parallel", type=int, default=8)
    p.add_argument("--timeout", type=float, default=180.0, help="Per-episode no-progress timeout (mimics are fast).")
    p.add_argument("--poll", type=float, default=0.5)
    p.add_argument("--real-only", action="store_true", help="Skip replay; only summarize real outcomes.")
    p.add_argument("--replot", action="store_true",
                   help="Skip replay; rebuild the figure from the saved report (means + CIs).")
    args = p.parse_args()

    if args.replot:
        summary = json.loads(OUT_REPORT.read_text(encoding="utf-8"))
        make_figure(summary)
        print(f"Replotted from {OUT_REPORT}")
        return 0

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    print(f"Manifest: {len(manifest)} entries")
    real = gather_real(manifest)
    print(f"Real outcomes loaded for {len(real)} episodes")

    if args.limit and args.limit > 0:
        keys = list(real.keys())[: args.limit]
        real = {k: real[k] for k in keys}
        print(f"Limited to first {len(real)} episodes")

    if args.real_only:
        print("real-only mode: skipping replay")
        return 0

    mimic = replay_mimics(args.base, real, parallel=args.parallel,
                          timeout_s=args.timeout, poll_s=args.poll)
    summary, _ = compare(real, mimic)

    OUT_REPORT.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"\nMatched {summary['n_matched_episodes']} episodes "
          f"({summary['n_setup_verified']} with verified-identical truth setup)")
    print(f"{'model':9s} {'metric':12s} {'real':>8s} {'mimic':>8s} {'|diff|':>8s} {'pairMAE':>8s}")
    for model in MODEL_ORDER:
        for k in ["catch_rate", "win_rate", "final_trust"]:
            rec = summary["per_model"].get(model, {}).get(k)
            if rec:
                print(f"{model:9s} {k:12s} {rec['real_mean']:8.3f} {rec['mimic_mean']:8.3f} "
                      f"{rec['abs_diff']:8.3f} {rec['paired_mae']:8.3f}")
    make_figure(summary)
    print(f"Report -> {OUT_REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
